spring:
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
    properties:
       "[schema.registry.url]": http://localhost:8081    # Confluent Schema Registry
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        "[specific.avro.reader]": true
