spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: sms-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        "[schema.registry.url]": http://localhost:8081
        "[specific.avro.reader]": true
        
logging:
  level:
    "[org.springframework.cloud.openfeign]": DEBUG
    "[com.example.service.InternalDBClient]": DEBUG
        
        

